# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\.source\error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorDialog(object):
    def setupUi(self, ErrorDialog):
        ErrorDialog.setObjectName("ErrorDialog")
        ErrorDialog.resize(293, 109)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ErrorDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ErrorDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_closeErrWindow = QtWidgets.QPushButton(ErrorDialog)
        self.pushButton_closeErrWindow.setDefault(True)
        self.pushButton_closeErrWindow.setObjectName("pushButton_closeErrWindow")
        self.gridLayout.addWidget(self.pushButton_closeErrWindow, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(ErrorDialog)
        QtCore.QMetaObject.connectSlotsByName(ErrorDialog)

    def retranslateUi(self, ErrorDialog):
        _translate = QtCore.QCoreApplication.translate
        ErrorDialog.setWindowTitle(_translate("ErrorDialog", "Ошибка"))
        self.label.setText(_translate("ErrorDialog", "Error_text"))
        self.pushButton_closeErrWindow.setText(_translate("ErrorDialog", "Закрыть"))
