# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\.source\auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(260, 132)
        AuthWindow.setStyleSheet("font: 10pt \"Arial\";")
        AuthWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(AuthWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 140))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VB_AuthInputs = QtWidgets.QVBoxLayout()
        self.VB_AuthInputs.setObjectName("VB_AuthInputs")
        self.VB_LoginData = QtWidgets.QVBoxLayout()
        self.VB_LoginData.setContentsMargins(-1, 0, 0, 0)
        self.VB_LoginData.setSpacing(0)
        self.VB_LoginData.setObjectName("VB_LoginData")
        self.L_LoginInputTitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.L_LoginInputTitle.setObjectName("L_LoginInputTitle")
        self.VB_LoginData.addWidget(self.L_LoginInputTitle)
        self.Input_Login = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Input_Login.setObjectName("Input_Login")
        self.VB_LoginData.addWidget(self.Input_Login)
        self.VB_AuthInputs.addLayout(self.VB_LoginData)
        self.VB_PassData = QtWidgets.QVBoxLayout()
        self.VB_PassData.setSpacing(2)
        self.VB_PassData.setObjectName("VB_PassData")
        self.L_PassInputTitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.L_PassInputTitle.setObjectName("L_PassInputTitle")
        self.VB_PassData.addWidget(self.L_PassInputTitle)
        self.Input_Pass = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Input_Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Input_Pass.setDragEnabled(False)
        self.Input_Pass.setObjectName("Input_Pass")
        self.VB_PassData.addWidget(self.Input_Pass)
        self.VB_AuthInputs.addLayout(self.VB_PassData)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.VB_AuthInputs.addWidget(self.pushButton)
        self.VB_AuthInputs.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.VB_AuthInputs)
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Авторизация"))
        self.L_LoginInputTitle.setText(_translate("AuthWindow", "Логин"))
        self.Input_Login.setPlaceholderText(_translate("AuthWindow", "Login"))
        self.L_PassInputTitle.setText(_translate("AuthWindow", "Пароль"))
        self.Input_Pass.setPlaceholderText(_translate("AuthWindow", "Password"))
        self.pushButton.setText(_translate("AuthWindow", "Вход"))
