# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\.source\edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditRowsWindow(object):
    def setupUi(self, EditRowsWindow):
        EditRowsWindow.setObjectName("EditRowsWindow")
        EditRowsWindow.resize(263, 235)
        self.centralwidget = QtWidgets.QWidget(EditRowsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.VBox_EditRows_Customers = QtWidgets.QVBoxLayout()
        self.VBox_EditRows_Customers.setSpacing(2)
        self.VBox_EditRows_Customers.setObjectName("VBox_EditRows_Customers")
        self.L_EditRow_CustomersTitle = QtWidgets.QLabel(self.centralwidget)
        self.L_EditRow_CustomersTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.L_EditRow_CustomersTitle.setObjectName("L_EditRow_CustomersTitle")
        self.VBox_EditRows_Customers.addWidget(self.L_EditRow_CustomersTitle)
        self.LE_EditRow_Customers = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_EditRow_Customers.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.LE_EditRow_Customers.setObjectName("LE_EditRow_Customers")
        self.VBox_EditRows_Customers.addWidget(self.LE_EditRow_Customers)
        self.gridLayout.addLayout(self.VBox_EditRows_Customers, 3, 0, 1, 1)
        self.VBox_EditRows_CityName = QtWidgets.QVBoxLayout()
        self.VBox_EditRows_CityName.setSpacing(2)
        self.VBox_EditRows_CityName.setObjectName("VBox_EditRows_CityName")
        self.L_EditRow_CityNameTitle = QtWidgets.QLabel(self.centralwidget)
        self.L_EditRow_CityNameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.L_EditRow_CityNameTitle.setObjectName("L_EditRow_CityNameTitle")
        self.VBox_EditRows_CityName.addWidget(self.L_EditRow_CityNameTitle)
        self.LE_EditRow_CityName = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_EditRow_CityName.setObjectName("LE_EditRow_CityName")
        self.VBox_EditRows_CityName.addWidget(self.LE_EditRow_CityName)
        self.gridLayout.addLayout(self.VBox_EditRows_CityName, 1, 0, 1, 1)
        self.VBox_EditRows_Zipcode = QtWidgets.QVBoxLayout()
        self.VBox_EditRows_Zipcode.setSpacing(2)
        self.VBox_EditRows_Zipcode.setObjectName("VBox_EditRows_Zipcode")
        self.L_EditRow_ZipcodeTitle = QtWidgets.QLabel(self.centralwidget)
        self.L_EditRow_ZipcodeTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.L_EditRow_ZipcodeTitle.setObjectName("L_EditRow_ZipcodeTitle")
        self.VBox_EditRows_Zipcode.addWidget(self.L_EditRow_ZipcodeTitle)
        self.LE_EditRow_Zipcode = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_EditRow_Zipcode.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LE_EditRow_Zipcode.setClearButtonEnabled(False)
        self.LE_EditRow_Zipcode.setObjectName("LE_EditRow_Zipcode")
        self.VBox_EditRows_Zipcode.addWidget(self.LE_EditRow_Zipcode)
        self.gridLayout.addLayout(self.VBox_EditRows_Zipcode, 2, 0, 1, 1)
        self.pushButton_EditRow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_EditRow.setObjectName("pushButton_EditRow")
        self.gridLayout.addWidget(self.pushButton_EditRow, 4, 0, 1, 1)
        self.VBox_EditRows_SubjectName = QtWidgets.QVBoxLayout()
        self.VBox_EditRows_SubjectName.setSpacing(2)
        self.VBox_EditRows_SubjectName.setObjectName("VBox_EditRows_SubjectName")
        self.L_EditRow_SubjectNameTitle = QtWidgets.QLabel(self.centralwidget)
        self.L_EditRow_SubjectNameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.L_EditRow_SubjectNameTitle.setObjectName("L_EditRow_SubjectNameTitle")
        self.VBox_EditRows_SubjectName.addWidget(self.L_EditRow_SubjectNameTitle)
        self.LE_EditRow_SubjectName = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_EditRow_SubjectName.setObjectName("LE_EditRow_SubjectName")
        self.VBox_EditRows_SubjectName.addWidget(self.LE_EditRow_SubjectName)
        self.gridLayout.addLayout(self.VBox_EditRows_SubjectName, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        EditRowsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EditRowsWindow)
        self.statusbar.setObjectName("statusbar")
        EditRowsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditRowsWindow)
        QtCore.QMetaObject.connectSlotsByName(EditRowsWindow)

    def retranslateUi(self, EditRowsWindow):
        _translate = QtCore.QCoreApplication.translate
        EditRowsWindow.setWindowTitle(_translate("EditRowsWindow", "Редактор данных"))
        self.L_EditRow_CustomersTitle.setText(_translate("EditRowsWindow", "Клиенты отделения"))
        self.L_EditRow_CityNameTitle.setText(_translate("EditRowsWindow", "Наименование города"))
        self.L_EditRow_ZipcodeTitle.setText(_translate("EditRowsWindow", "Индекс"))
        self.pushButton_EditRow.setText(_translate("EditRowsWindow", "Изменить"))
        self.L_EditRow_SubjectNameTitle.setText(_translate("EditRowsWindow", "Наименование субъекта РФ"))
