# Form implementation generated from reading ui file 'UI/source/auth.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(262, 182)
        MainWindow.setStyleSheet("font: 10pt \"Arial\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 161))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VB_AuthInputs = QtWidgets.QVBoxLayout()
        self.VB_AuthInputs.setObjectName("VB_AuthInputs")
        self.VB_LoginData = QtWidgets.QVBoxLayout()
        self.VB_LoginData.setContentsMargins(-1, 0, 0, 0)
        self.VB_LoginData.setSpacing(2)
        self.VB_LoginData.setObjectName("VB_LoginData")
        self.L_LoginInputTitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.L_LoginInputTitle.setObjectName("L_LoginInputTitle")
        self.VB_LoginData.addWidget(self.L_LoginInputTitle)
        self.Input_Login = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Input_Login.setObjectName("Input_Login")
        self.VB_LoginData.addWidget(self.Input_Login)

        self.VB_AuthInputs.addLayout(self.VB_LoginData)
        self.VB_PassData = QtWidgets.QVBoxLayout()
        self.VB_PassData.setSpacing(2)
        self.VB_PassData.setObjectName("VB_PassData")
        self.L_PassInputTitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.L_PassInputTitle.setObjectName("L_PassInputTitle")

        self.VB_PassData.addWidget(self.L_PassInputTitle)
        self.Input_Pass = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Input_Pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Input_Pass.setDragEnabled(False)
        self.Input_Pass.setObjectName("Input_Pass")
        self.VB_PassData.addWidget(self.Input_Pass)
        self.VB_AuthInputs.addLayout(self.VB_PassData)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.VB_AuthInputs.addWidget(self.pushButton)
        self.VB_AuthInputs.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.VB_AuthInputs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.L_LoginInputTitle.setText(_translate("MainWindow", "Логин"))
        self.Input_Login.setPlaceholderText(_translate("MainWindow", "Login"))
        self.L_PassInputTitle.setText(_translate("MainWindow", "Пароль"))
        self.Input_Pass.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Вход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AuthWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
